### ISSUE TITLE
[Feature Request] 希望MiraiDeviceGenerator能自定义Json文件路径

### ISSUE THREAD

**Issue by YUCLing** [cssxsh/mirai-device-generator#2]
https://github.com/cssxsh/mirai-device-generator/blob/590d125b903e15654c4c1b5339c5b451c8a4966b/src/main/kotlin/xyz/cssxsh/mirai/device/MiraiDeviceGenerator.kt#L42

现在device.json路径是写死在Generator里面的，希望能添加一些方法来修改路径。例如添加一个新的constructor？

**Comment by cssxsh** [comment]
应用场景？

**Comment by YUCLing** [comment]
> 应用场景？

方便在同一个workdir使用多个不同的device.json

**Comment by cssxsh** [comment]
不是应该为每个 Bot 设置独立的 workingDir 吗

**Comment by YUCLing** [comment]
弄了个自动换号的功能，能直接换device.json方便，毕竟也要用同一个KFCFactory.json什么的😬

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-device-generator/blob/23f69ad2091461a745fdb4988e8d5f23b3a07df3/src/main/kotlin/xyz/cssxsh/mirai/device/MiraiDeviceGenerator.kt#L51

load 是方便 `configuration.deviceInfo = generator::load` 的产物
你可以自行封装 generate
